const assert = require('node:assert/strict');
const Module = require('node:module');
const path = require('node:path');
const ts = require('typescript');
const fs = require('node:fs');
const root = path.resolve(__dirname, '..');
require.extensions['.ts'] = (m, f) => m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true } }).outputText, f);
let cookie, profile, reads = 0, creates = 0;
const original = Module._load;
Module._load = function(name, parent, main) {
  if (name === 'next/headers') return { cookies: async () => ({ get: () => cookie ? {value:cookie} : undefined }) };
  if (name === '@/lib/db' || (name === './db' && parent.filename.endsWith('/lib/auth.ts'))) return { pool: { query: async (query) => { reads++; if (query.includes('auth_user_id')) return { rows: profile ? [profile] : [] }; if (query.includes('sucursales')) return {rows:[{id:7}], rowCount:1}; if (query.startsWith('UPDATE')) return {rowCount:1}; return {rows:[]}; } } };
  if (name === '@/lib/supabase-server') return { authClient: () => ({auth:{admin:{createUser:async()=>{creates++;return {data:{user:{id:'new-user'}}};},deleteUser:async()=>({error:null})}}}) };
  return original.call(this, name.startsWith('@/') ? path.join(root,name.slice(2)) : name, parent, main);
};
process.env.AUTH_SECRET = 'test-only-secret-that-is-at-least-32-characters';
process.env.ADMIN_EMAIL = 'admin@example.test';
process.env.ADMIN_PASSWORD = 'test-only-password';
const {signSession, verifySession} = require('../lib/session.ts');
const {canCreateRole, canAccessPage} = require('../lib/roles.ts');
const auth = require('../lib/auth.ts');
const login = require('../app/api/auth/login/route.ts');
const register = require('../app/api/auth/register/route.ts');
const req = (body, origin='http://localhost') => new Request('http://localhost/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify(body)});
(async()=>{
  for (const actor of [0,1,2,3,4]) for(const target of [0,1,2,3,4]) assert.equal(canCreateRole(actor,target), actor===1 && [2,3].includes(target) || actor===2 && target===3);
  assert.equal(canAccessPage(3,'/usuarios'),false); assert.equal(canAccessPage(3,'/sales'),true);
  const token=signSession({kind:'admin',sub:process.env.ADMIN_EMAIL});
  assert.ok(verifySession(token)); assert.equal(verifySession(token+'x'),null);
  const jwt=require('jsonwebtoken');
  assert.equal(verifySession(jwt.sign({kind:'admin',sub:process.env.ADMIN_EMAIL}, process.env.AUTH_SECRET, {expiresIn:-1,issuer:'pacifico',audience:'pacifico-web'})),null);
  cookie=undefined; await assert.rejects(auth.currentUser(),e=>e.status===401);
  let response=await login.POST(req({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD}));
  assert.equal(response.status,200); assert.match(response.headers.get('set-cookie'),/HttpOnly/); assert.equal(reads,0);
  response=await login.POST(req({email:process.env.ADMIN_EMAIL,password:'wrong'}));assert.equal(response.status,401);
  cookie=token; assert.equal((await auth.currentUser()).id,0);assert.equal(reads,0);
  const body={name:'Ana',last_name:'Prueba',email:'ana@example.test',password:'test-password',rol_id:2,branch_id:7};
  assert.equal((await register.POST(req(body))).status,201);
  assert.equal((await register.POST(req({...body,rol_id:1}))).status,403);
  assert.equal((await register.POST(req(body,'https://other.test'))).status,403);
  cookie=signSession({kind:'staff',sub:'staff-id'});
  profile={id:4,nombre:'Gerente',rol_id:2,sucursal_id:7,estado:true};
  assert.equal((await register.POST(req(body))).status,403);
  assert.equal((await register.POST(req({...body,rol_id:3,branch_id:8}))).status,403);
  assert.equal((await register.POST(req({...body,rol_id:3}))).status,201);
  profile.rol_id=3; const before=creates;
  assert.equal((await register.POST(req({...body,rol_id:3}))).status,403);assert.equal(creates,before);
  profile.estado=false;await assert.rejects(auth.currentUser(),e=>e.status===403);
  profile.estado=true;profile.rol_id=1;await assert.rejects(auth.currentUser(),e=>e.status===403);
  cookie=undefined;assert.equal((await register.POST(req(body))).status,401);
  console.log('OK: matriz de roles, JWT inválido/expirado, ADMIN sin BD, cookie HttpOnly, login incorrecto, registro autorizado, sucursal, CSRF, cajero, inactivos y admin de BD rechazado. Dependencias externas simuladas.');
})().catch(e=>{console.error(e);process.exitCode=1});
